# MLB Stadium coordinates and metadata for weather lookups

STADIUMS = {
    'Arizona Diamondbacks': {'name': 'Chase Field', 'lat': 33.4455, 'lon': -112.0667, 'city': 'Phoenix, AZ', 'dome': True},
    'Atlanta Braves': {'name': 'Truist Park', 'lat': 33.8908, 'lon': -84.4678, 'city': 'Cumberland, GA', 'dome': False},
    'Baltimore Orioles': {'name': 'Camden Yards', 'lat': 39.2839, 'lon': -76.6218, 'city': 'Baltimore, MD', 'dome': False},
    'Boston Red Sox': {'name': 'Fenway Park', 'lat': 42.3467, 'lon': -71.0972, 'city': 'Boston, MA', 'dome': False},
    'Chicago Cubs': {'name': 'Wrigley Field', 'lat': 41.9484, 'lon': -87.6553, 'city': 'Chicago, IL', 'dome': False},
    'Chicago White Sox': {'name': 'Guaranteed Rate Field', 'lat': 41.8300, 'lon': -87.6339, 'city': 'Chicago, IL', 'dome': False},
    'Cincinnati Reds': {'name': 'Great American Ball Park', 'lat': 39.0979, 'lon': -84.5082, 'city': 'Cincinnati, OH', 'dome': False},
    'Cleveland Guardians': {'name': 'Progressive Field', 'lat': 41.4962, 'lon': -81.6852, 'city': 'Cleveland, OH', 'dome': False},
    'Colorado Rockies': {'name': 'Coors Field', 'lat': 39.7559, 'lon': -104.9942, 'city': 'Denver, CO', 'dome': False},
    'Detroit Tigers': {'name': 'Comerica Park', 'lat': 42.3390, 'lon': -83.0485, 'city': 'Detroit, MI', 'dome': False},
    'Houston Astros': {'name': 'Minute Maid Park', 'lat': 29.7572, 'lon': -95.3556, 'city': 'Houston, TX', 'dome': True},
    'Kansas City Royals': {'name': 'Kauffman Stadium', 'lat': 39.0517, 'lon': -94.4803, 'city': 'Kansas City, MO', 'dome': False},
    'Los Angeles Angels': {'name': 'Angel Stadium', 'lat': 33.8003, 'lon': -117.8827, 'city': 'Anaheim, CA', 'dome': False},
    'Los Angeles Dodgers': {'name': 'Dodger Stadium', 'lat': 34.0739, 'lon': -118.2400, 'city': 'Los Angeles, CA', 'dome': False},
    'Miami Marlins': {'name': 'loanDepot park', 'lat': 25.7781, 'lon': -80.2197, 'city': 'Miami, FL', 'dome': True},
    'Milwaukee Brewers': {'name': 'American Family Field', 'lat': 43.0280, 'lon': -87.9712, 'city': 'Milwaukee, WI', 'dome': True},
    'Minnesota Twins': {'name': 'Target Field', 'lat': 44.9817, 'lon': -93.2778, 'city': 'Minneapolis, MN', 'dome': False},
    'New York Mets': {'name': 'Citi Field', 'lat': 40.7571, 'lon': -73.8458, 'city': 'New York, NY', 'dome': False},
    'New York Yankees': {'name': 'Yankee Stadium', 'lat': 40.8296, 'lon': -73.9262, 'city': 'New York, NY', 'dome': False},
    'Oakland Athletics': {'name': 'Oakland Coliseum', 'lat': 37.7516, 'lon': -122.2005, 'city': 'Oakland, CA', 'dome': False},
    'Philadelphia Phillies': {'name': 'Citizens Bank Park', 'lat': 39.9061, 'lon': -75.1665, 'city': 'Philadelphia, PA', 'dome': False},
    'Pittsburgh Pirates': {'name': 'PNC Park', 'lat': 40.4469, 'lon': -80.0057, 'city': 'Pittsburgh, PA', 'dome': False},
    'San Diego Padres': {'name': 'Petco Park', 'lat': 32.7076, 'lon': -117.1570, 'city': 'San Diego, CA', 'dome': False},
    'San Francisco Giants': {'name': 'Oracle Park', 'lat': 37.7786, 'lon': -122.3893, 'city': 'San Francisco, CA', 'dome': False},
    'Seattle Mariners': {'name': 'T-Mobile Park', 'lat': 47.5914, 'lon': -122.3328, 'city': 'Seattle, WA', 'dome': True},
    'St. Louis Cardinals': {'name': 'Busch Stadium', 'lat': 38.6226, 'lon': -90.1928, 'city': 'St. Louis, MO', 'dome': False},
    'Tampa Bay Rays': {'name': 'Tropicana Field', 'lat': 27.7682, 'lon': -82.6534, 'city': 'St. Petersburg, FL', 'dome': True},
    'Texas Rangers': {'name': 'Globe Life Field', 'lat': 32.7473, 'lon': -97.0831, 'city': 'Arlington, TX', 'dome': True},
    'Toronto Blue Jays': {'name': 'Rogers Centre', 'lat': 43.6414, 'lon': -79.3894, 'city': 'Toronto, ON', 'dome': True},
    'Washington Nationals': {'name': 'Nationals Park', 'lat': 38.8730, 'lon': -77.0074, 'city': 'Washington, DC', 'dome': False},
}
